### ISSUE TITLE
Window Size

### ISSUE THREAD

**Issue by DANW999** [tassaron2/symlink-editor#2]
Thank you for this application! I am not sure why finding a symlink GUI seems to be so rare. Just one question - this application does not seem to scale to the full size of the screen if you maximize it as per the screenshot below - is there anyway to rectify this?
![Symlink Editor](https://user-images.githubusercontent.com/91419908/153483584-4b1b6bd6-a639-439b-ba82-994c2dc3c06f.png)

**Comment by tassaron** [comment]
Sorry, it's like that because I was bad at writing code when I made this program in 2017 😂

**I fixed it now** so if you download again it should now expand when resized.

This program needs a complete rewrite and I decided to stop using GTK years ago because the developer experience is really poor. When I have free time someday I hope to make this program new and shiny, Until then I'm glad some people are finding it useful! Thank you for submitting this issue :)

**Comment by DANW999** [comment]
It works perfectly, I would like to thank you for you work and addressing this so quickly!
